#ifndef __VirtRegsMap_h__
#define __VirtRegsMap_h__

#define SYS_WORD_SIZE 4

enum VIRTUAL_SYSTEM_REGISTER_MAP
{
    SYS_MEM_TYPE,
    SYS_MEM_SIZE = SYS_MEM_TYPE + SYS_WORD_SIZE,
    SYS_ERRORS_COUNT = SYS_MEM_SIZE + SYS_WORD_SIZE,
    SYS_COMPILE_TIME = SYS_ERRORS_COUNT + SYS_WORD_SIZE,
    SYS_HANDLERS_COUNT = SYS_COMPILE_TIME + SYS_WORD_SIZE,
    SYS_RESERVED_3 = SYS_HANDLERS_COUNT + SYS_WORD_SIZE,
};

enum VIRTUAL_USER_REGISTER_MAP
{
    REG_LMOTOR = SYS_RESERVED_3 + VIRT_REG_USER_WORD_SIZE,
    REG_RMOTOR = REG_LMOTOR + VIRT_REG_USER_WORD_SIZE,
    REG_MQTT_PERIOD = REG_RMOTOR + VIRT_REG_USER_WORD_SIZE,
    USER_REG3 = REG_MQTT_PERIOD + VIRT_REG_USER_WORD_SIZE,
    USER_REG4 = USER_REG3 + VIRT_REG_USER_WORD_SIZE,
};

#endif //__VirtRegsMap_h__